[BE/#603] 채팅방 나갔다가 들어오면 이전 채팅 안보이게 구현
boostcampwm2023/iOS05-Village pull request #604
Opened 2024-01-11 07:37 UTC by namewhat99

## 이슈
- #603 

## 체크리스트
- [x] 채팅방 나가기 
- [x] 돌아오면 이전 채팅 안보임

2024-01-11 13:26 UTC, koomin1227 requested changes

2024-01-11 13:37 UTC, namewhat99 commented on BE/src/chat/chat.service.ts
>      });
그러면 checkAuth 를 맨 처음으로 옮겨서 처음에 해당 방이 존재하는지와 해당 방에 존재하는 사람이 맞는지 확인 후에 아래 로직들을 실행하는 방식으로 바꾸겠습니당~

2024-01-11 13:47 UTC, namewhat99 commented on BE/src/chat/chat.service.ts
> +    ) {
url 로 접근하는 부분때문인가요? 자신이 숨긴 채팅방을 url 을 통해 400 혹은 409 로 던지면 될 것 같은데 어케 생각하시나요?

2024-01-13 04:23 UTC, namewhat99 commented on BE/src/chat/chat.service.ts
> +
<img width="825" alt="image" src="https://github.com/boostcampwm2023/iOS05-Village/assets/61961553/a5c7768e-544b-419b-9ff7-149e4f2b771d">

2024-01-13 04:27 UTC, namewhat99 commented on BE/src/chat/chat.service.ts
> +
실험을 해 본 결과인데 현재 응답시간 자체가 평균적으로 30ms 로 좋은 편이기도 하고 해당 사람의 나간 시간을 얻기위해 DB 에 접근해서 시간을 얻고 다시 한번 DB 에 접근하는것 보다는 서버에서 가져온 데이터를 처리해서 주는게 현재로써는 조금 더 좋을거라고 생각이 드네요. 나중에 혹시 이에 관해서 문제가 생기면 말씀해주신 방법으로 바꿔보는것도 좋을 것 같습니다

2024-01-13 04:28 UTC, namewhat99 commented on BE/src/chat/chat.service.ts
> +
메서드 분리는 진행하겠읍니다~

2024-01-14 05:56 UTC, namewhat99 commented on BE/src/chat/chat.service.ts
> +
주석 처리 해 놓은건 페이지네이션 미리 적용해본건데 이건 나중에 고치고 빼겠읍니다

2024-01-14 07:54 UTC, namewhat99 commented on BE/src/chat/chat.service.ts
> +
이 부분 채팅 페이지네이션 미리 적용해본건데 나중에 이걸로 바꾸겠습니다

2024-01-14 08:16 UTC, koomin1227 approved these changes

2024-01-14 14:00 UTC, merged